### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by manunoly** [only2dhir/angular6-hide-sidenav-example#1]
Thanks for share your code, i try to run your example and i getting this error

ERROR in Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
ℹ ｢wdm｣: Failed to compile.

Angular CLI: 6.0.8
Node: 8.11.4
OS: linux x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@angular/platform-server          6.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

Ubuntu 16.04.5 LT

nodejs -v
v8.11.4

**Comment by soorajvinodan** [comment]
> Thanks for share your code, i try to run your example and i getting this error
> 
> ERROR in Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
> ℹ ｢wdm｣: Failed to compile.
> 
> Angular CLI: 6.0.8
> Node: 8.11.4
> OS: linux x64
> Angular: 6.0.9
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> ## Package Version
> @angular-devkit/architect 0.6.8
> @angular-devkit/build-angular 0.6.8
> @angular-devkit/build-optimizer 0.6.8
> @angular-devkit/core 0.6.8
> @angular-devkit/schematics 0.6.8
> @angular/cdk 6.4.0
> @angular/cli 6.0.8
> @angular/material 6.4.0
> @angular/platform-server 6.1.0
> @ngtools/webpack 6.0.8
> @schematics/angular 0.6.8
> @schematics/update 0.6.8
> rxjs 6.2.2
> typescript 2.7.2
> webpack 4.8.3
> 
> Ubuntu 16.04.5 LT
> 
> nodejs -v
> v8.11.4

Did You find the solution for it? I am still getting the same error while complying it

**Comment by zdong11** [comment]
Can I have a try?

**Comment by only2dhir** [comment]
yes. Its fixed now. File changed - app.module.ts and main.ts
